config/routes.rb
MuscTfcbt::Application.routes.draw do

  get "home/index"
  root :to => "home#index"

  devise_for :providers

  get '/providers/csv' => 'providers#export', as: 'export_providers'

  get '/providers/:id/prepare' => 'providers#prepare', as: 'prepare_providers'
  
  resources :providers do
    resources :patients, only: [:new, :create]
  end
  
  resources :patients, only: [:show, :edit, :update] do
    resources :assignments, only: [:index]
  end
  
  resources :decks, only: [:index, :edit, :update]
  resources :section_questions, only: [:edit, :update]

  put 'patients/:id/assign/:homework_id' => 'patients#assign_homework', as: 'assign_patient_homework'
  put 'patients/:id/deactivate' => 'patients#deactivate', as: 'deactivate_patient'
  put 'patients/:id/activate' => 'patients#activate', as: 'activate_patient'
  put 'patients/:id/start' => 'patients#start_session', as: 'start_patient_session'
  
  resources :chapters, only: [:index, :edit, :show, :update] do
    resources :sections, only: [:show, :create, :destroy]
  end
  
  resources :prepares, only: [:show]
  
  put 'chapters/:chapter_id/sections/:id/finish' => 'sections#finish', as: 'finish_chapter_section'
  put 'chapters/:chapter_id/sections/:id/interaction' => 'sections#interaction', as: 'interaction_chapter_section'
  
  get 'content/edit' => 'content#edit', as: 'edit_content'
  post 'content/edit' => 'content#update_audio_url', as: 'update_audio_url'
  patch 'content' => 'content#update'
  
  get 'homework_category/:id/list' => 'homework_category#list', as: 'list_homework_category'

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # bwj removed :rememberable, :registerable  until we get there
  devise :database_authenticatable, :trackable, :validatable, :timeoutable, :recoverable
         
  validates   :name, presence: true, length: { maximum: 100 }
  validates   :email, presence: true, uniqueness: {case_sensitive: false }
  validates   :password, presence: true, length: { minimum: 8 }, on: :create
  validates   :password, length: { minimum: 8 }, on: :update, allow_blank: true
  
  belongs_to  :profession
  belongs_to  :degree
  belongs_to  :experience
  
  has_many    :patients, :dependent => :destroy
  has_many    :decks, :dependent => :destroy
  
  before_save { self.email = email.downcase }
  
  after_create :set_decks
    def set_decks
      provider_id = self.id
      Deck.where(original: true).each do |deck|
        deck_copy = deck.deep_clone :include => {:cards => :notes}
        deck_copy.provider_id = provider_id
        deck_copy.original = false
        deck_copy.save
      end
    end
end

app/controllers/providers_controller.rb
require 'csv'

class ProvidersController < ApplicationController
  
  before_action :authenticate_provider!
  before_action :check_authorization
  before_action :check_admin, except: [:show, :prepare]
  
  def index
    @providers = Provider.all.where.not(id: current_provider.id)
  end
  
  def show
    @provider = Provider.find(params[:id])
    
    provider_session[:patient_id] = nil
  end
  
  def prepare
    @provider = Provider.find(params[:id])
    provider_session[:patient_id] = nil
  end
  
  def new
    @provider = Provider.new()
  end
  
  def create
    @provider = Provider.new(provider_params)
    
    if @provider.save
      redirect_to providers_path
    else
      flash[:error] = @provider.errors.full_messages
      render 'new'
    end
  end
  
  def edit
    @provider = Provider.find(params[:id])
  end
  
  def update
    @provider = Provider.find(params[:id])
    
    if @provider.update_without_password(provider_params)
      redirect_to providers_path
    else
      render 'edit'
    end
  end
  
  def destroy
    Provider.destroy(params[:id])
    redirect_to :back
  end
  
  def export
    @csv = ''
    
    @csv << CSV.generate_line([
      'provider id', 
      'provider name',
      'provider e-mail',
      'provider degree',
      'provider country',
      'provider state (if US)',
      'provider profession',
      'provider years of experience',
      'patient id',
      'patient gender',
      'patient age',
      'patient race',
      'patient ethnicity',
      'patient index trauma',
      'patient trauma #2',
      'patient trauma #3',
      'patient trauma #4',
      'chapter 1 use',
      'chapter 1 first date',
      'chapter 1 last date',
      'chapter 1 deck 1',
      'chapter 1 deck 2',
      'chapter 1 deck 3',
      'chapter 1 deck 4',
      'chapter 1 deck 5',
      'chapter 1 deck 6',
      'chapter 1 deck 7',
      'chapter 1 deck 8',
      'chapter 2 use',
      'chapter 2 first date',
      'chapter 2 last date',
      'chapter 2 dropdown item 1 answer',
      'chapter 2 dropdown item 2 answer',
      'chapter 2 dropdown item 3 answer',
      'chapter 2 dropdown item 4 answer',
      'chapter 2 dropdown item 5 answer',
      'chapter 2 dropdown item 6 answer',
      'chapter 2 dropdown item 7 answer',
      'chapter 2 dropdown item 8 answer',
      'chapter 2 dropdown item 9 answer',
      'chapter 2 dropdown item 10 answer',
      'chapter 2 dropdown item 11 answer',      
      'chapter 3 use',
      'chapter 3 first date',
      'chapter 3 last date',
      'chapter 3 complete front (boy)',
      'chapter 3 complete back (boy)',
      'chapter 3 complete front (girl)',
      'chapter 3 complete back (girl)',
      'chapter 4 use',
      'chapter 4 first date',
      'chapter 4 last date',
      'chapter 4 deck 1',
      'chapter 4 deck 2',
      'chapter 4 deck 3',
      'chapter 4 deck 4',
      'chapter 4 deck 5',
      'chapter 5 use',
      'chapter 5 first date',
      'chapter 5 last date',
      'chapter 6 use',
      'chapter 6 first date',
      'chapter 6 last date',
      'chapter 7 use',
      'chapter 7 first date',
      'chapter 7 last date',
      'chapter 8 use',
      'chapter 8 first date',
      'chapter 8 last date',
      'chapter 8 complete',
      'chapter 9 use',
      'chapter 9 first date',
      'chapter 9 last date',
      'chapter 10 use',
      'chapter 10 first date',
      'chapter 10 last date',
      'chapter 11 use',
      'chapter 11 first date',
      'chapter 11 last date',
      'chapter 11 deck 1',
      'chapter 11 deck 2',
      'chapter 11 deck 3',
      'chapter 11 deck 4',
      'chapter 11 deck 5',
      'chapter 11 deck 6'
    ])
    
    chapter_first_section = Hash[Section.where(sequence: 1).map{|s| [s.chapter.display_order, s.id]}]
    cognitive_coping_chapter = Chapter.where(display_order: 8).first
    last_coping_section = Section.where(chapter_id: cognitive_coping_chapter.id).order('sequence DESC').first
    
    Provider.all.each do |provider|
      provider.patients.each do |patient|
        @csv << CSV.generate_line([
          provider.id, 
          provider.name, 
          provider.email,
          provider.degree.try(:description),
          provider.country_code,
          provider.state_code,
          provider.profession.try(:description),
          provider.experience.try(:description),
          patient.lookup_id,
          patient.gender.try(:description),
          patient.age,
          patient.race.try(:description),
          patient.ethnicity.try(:description),
          patient.trauma1.try(:description),
          patient.trauma2.try(:description),
          patient.trauma3.try(:description),
          patient.trauma4.try(:description),
          patient.interactions.where(section_id: chapter_first_section[1], description: 'Visit').count,
          patient.interactions.where(section_id: chapter_first_section[1]).order('created_at ASC').first.try(:created_at),
          patient.interactions.where(section_id: chapter_first_section[1]).order('created_at DESC').first.try(:created_at),
          patient.interactions.where(section_id: chapter_first_section[1] + 1, description: 'Response', data: '1', data_key: 'deck_index').any? ? 'selected' : 'not selected',
          patient.interactions.where(section_id: chapter_first_section[1] + 1, description: 'Response', data: '2', data_key: 'deck_index').any? ? 'selected' : 'not selected',
          patient.interactions.where(section_id: chapter_first_section[1] + 1, description: 'Response', data: '3', data_key: 'deck_index').any? ? 'selected' : 'not selected',
          patient.interactions.where(section_id: chapter_first_section[1] + 1, description: 'Response', data: '4', data_key: 'deck_index').any? ? 'selected' : 'not selected',
          patient.interactions.where(section_id: chapter_first_section[1] + 1, description: 'Response', data: '5', data_key: 'deck_index').any? ? 'selected' : 'not selected',
          patient.interactions.where(section_id: chapter_first_section[1] + 1, description: 'Response', data: '6', data_key: 'deck_index').any? ? 'selected' : 'not selected',
          patient.interactions.where(section_id: chapter_first_section[1] + 1, description: 'Response', data: '7', data_key: 'deck_index').any? ? 'selected' : 'not selected',
          patient.interactions.where(section_id: chapter_first_section[1] + 1, description: 'Response', data: '8', data_key: 'deck_index').any? ? 'selected' : 'not selected',        
          patient.interactions.where(section_id: chapter_first_section[2], description: 'Visit').count,
          patient.interactions.where(section_id: chapter_first_section[2]).order('created_at ASC').first.try(:created_at),
          patient.interactions.where(section_id: chapter_first_section[2]).order('created_at DESC').first.try(:created_at),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '1').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '2').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '3').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '4').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '5').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '6').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '7').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '8').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '9').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '10').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[2] + 1, description: 'Response', data_key: '11').order('created_at DESC').first.try(:data),
          patient.interactions.where(section_id: chapter_first_section[3], description: 'Visit').count,
          patient.interactions.where(section_id: chapter_first_section[3]).order('created_at ASC').first.try(:created_at),
          patient.interactions.where(section_id: chapter_first_section[3]).order('created_at DESC').first.try(:created_at),
          patient.interactions.where(section_id: chapter_first_section[3] + (patient.gender_id === 1 ? 1 : 3), description: 'Visit').any? ? 1 : 0,
          patient.interactions.where(section_id: chapter_first_section[3] + (patient.gender_id === 1 ? 2 : 4), description: 'Visit').any? ? 1 : 0,
          patient.interactions.where(section_id: chapter_first_section[3] + (patient.gender_id === 1 ? 3 : 1), description: 'Visit').any? ? 1 : 0,
          patient.interactions.where(section_id: chapter_first_section[3] + (patient.gender_id === 1 ? 4 : 2), description: 'Visit').any? ? 1 : 0,
          patient.interactions.where(section_id: chapter_first_section[4], description: 'Visit').count,
          patient.interactions.where(section_id: chapter_first_section[4]).order('created_at ASC').first.try(:created_at),
          patient.interactions.where(section_id: chapter_first_section[4]).order('created_at DESC').first.try(:created_at),

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_provider.html.erb
<div class="tame-stage">

<div class="input-row">
	<div class="half">
		<%= f.label :name, "Full Name" %>
		<%= f.text_field :name, :required => true, :autofocus => true %>
	</div>
	<div class="half end">
		<%= f.label :email %>
		<%= f.text_field :email, :required => true %>
	</div>
</div>
<div class="input-row">
	<div class="half">
		<%= f.label :password %>
		<% if params[:action] == 'new' %>
			<%= f.password_field :password, :required => true %>
		<% else %>
			<%= f.password_field :password %>
		<% end %>
	</div>
	<div class="half end">
		<%= f.label :password_confirmation %>
		<% if params[:action] == 'new' %>
			<%= f.password_field :password_confirmation, :required => true %>
		<% else %>
			<%= f.password_field :password_confirmation %>
		<% end %>
	</div>
</div>
<div class="input-row">
	<div class="half">
		<%= f.label :degree %>
		<%= collection_select(:provider, :degree_id, Degree.all, :id, :description, :required => true, :include_blank => 'Select an option')%>
	</div>
	<div class="half end">
		<%= f.label :profession %>
		<%= collection_select(:provider, :profession_id, Profession.all, :id, :description, :required => true, :include_blank => 'Select an option')%>
	</div>
</div>
<div class="input-row">
	<div class="half">
		<%= f.label :experience %>
		<%= collection_select(:experience, :experience_id, Experience.all, :id, :description, :required => true, :include_blank => 'Select an option')%>
	</div>
	<div class="half end">
	</div>
</div>
<div class="input-row">
	<div class="half">
		<%= f.label :country_code, "Country" %>
		<%= f.country_select :country_code, {priority: %w[US CA]} %>
	</div>
	<div class="half end">
		<%= f.label :state_code, "State" %>
		<div class='state-code-selectbox'>
			<%= f.collection_select :state_code, Carmen::Country.coded("US").subregions, :name, :name, {include_blank: 'Select an option'} %>
		</div>
	</div>
</div>

</div>

app/views/providers/edit.html.erb
<%
	provide(:title, 'Administration')
	provide(:body_class, 'provider-info edit')
%>
<div class="stage-top">
	<h2>Edit Provider Profile</h2>
	<div class="error-explanation">
		<% @provider.errors.full_messages.each do |m| %>
		<p><%= m %></p>
		<% end %>
	</div>
</div>
<div class="stage-bottom">
	<%= form_for @provider do |f| %>
		<%= render partial: 'provider', locals: {f: f} %>
	<% end %>
	
	<div class="stage-controls clear">
		<a href="#" class="button green save"><span>Save Changes</span></a>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
		<span>Back</span>
		<% end %>
	</div>
</div>

app/views/providers/index.html.erb
<%
	provide(:title, 'Administration')
	provide(:body_class, 'providers-info')
%>
<div class="stage-bottom">

<div class="tame-stage">

	<table>
		<caption>Providers</caption>
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @providers.each do |provider| %>
			<tr>
				<td><%= provider.name %></td>
				<td><%= provider.email %></td>
				<td>
					<%= link_to 'Show', provider_path(provider) %>
					<span> - </span>
					<%= link_to 'Edit', edit_provider_path(provider) %>
					<span> - </span>
					<%= link_to 'Delete', provider_path(provider), data: {confirm: "Are you sure you want to delete this provider?\nAll associated patient data will also be deleted."}, :method => :delete %>
				</td>
			</tr>
			<% end%>
		</tbody>
	</table>
	
</div>

	<div class="stage-controls clear">
		<%= link_to new_provider_path, class: 'button green' do %>
		<span>Create New Provider</span>
	<% end %>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
		<span>Back</span>
		<% end %>
	</div>

</div>

app/views/providers/new.html.erb
<%
	provide(:title, 'Administration')
	provide(:body_class, 'provider-info')
%>
<div class="stage-top">
	<h2>Provider Profile</h2>
</div>
<div class="stage-bottom">
	<% flash.each do |name, message| %>
	<p><%= message %></p>
	<% end %>
	
	<%= form_for @provider do |f| %>
		<%= render partial: 'provider', locals: {f: f} %>
	<% end %>
	
	<div class="stage-controls clear">
		<a href="#" class="button green"><span onclick="document.getElementById('new_provider').submit();">Create New Provider</span></a>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
		<span>Back</span>
		<% end %>
	</div>
</div>

app/views/providers/prepare.html.erb
<%
	provide(:body_class, 'misc patient provider chapters')
	provide(:title, "Provider Preparation")
%>

<div class="stage-top">
	<h2><%= @provider.name %></h2>
</div>
<div class="stage-bottom">
	<h3>Choose a chapter.</h3>

	<div class="tame-stage clear">

		<div class="chapter-buttons clear">
		<% Chapter.all.order("display_order ASC").each do |chapter| %>
			<% if chapter.first_vimeo_url %>
				<%= link_to content_tag(:span, chapter.display_name), chapter_path(chapter.id), class: 'button green' %>
			<% end %>
		<% end %>
		</div>

	</div>

	<div class="stage-controls clear">
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
			<span>Back</span>
		<% end %>
	</div>

</div>

app/views/providers/show.html.erb
<%
provide(:body_class, 'misc provider-home')
provide(:title, 'Provider - main menu')
%>

<div class="stage-bottom clear">
	<% if current_provider.admin? %>
	<div class="left">
		<h2>eTF-CBT</h2>
		<h6>Medical University of South Carolina</h6>
		<h3 class="color-green">Welcome, <%= @provider.name %>.</h3>
		<div class="clear">
			<%= link_to providers_path, class: 'button' do %>
				<span>Manage providers</span>
			<% end %>
		</div>
		<div class="clear">
			<%= link_to edit_content_path, class: 'button' do %>
				<span>Manage content</span>
			<% end %>
		</div>
		<div class="clear">
			<%= link_to export_providers_path, class: 'button' do %>
				<span>Export session data</span>
			<% end %>
		</div>
		<div class="clear">
			<%= link_to destroy_provider_session_path, class: 'button', :method => :delete do%>
				<span>Log out</span>
			<% end %>
		</div>
	</div>
	<div class="right">
	</div>
	<% else %>
	<div class="left">
		<h2>eTF-CBT</h2>
		<h6>Medical University of South Carolina</h6>
		<h3 class="color-green"><%= @provider.name %></h3>
		<div class="clear">
			<%= link_to new_provider_patient_path(@provider), class: 'button create' do %>
				<span>Create New Patient</span>
			<% end %>
		</div>
		<div class="clear">
			<%= link_to decks_path, class: 'button create' do %>
				<span>Edit Cards</span>
			<% end %>

			<%= link_to destroy_provider_session_path, class: 'button', :method => :delete do%>
				<span>Log out</span>
			<% end %>
		</div>
		<div class="clear">
			
		</div>
	</div>
	<div class="right">

		<h3>Active Patients</h3>
		<select name="active-patients">
			<option value="">Please Select</option>
			<% @provider.patients.where(is_active: true).each do |patient| %>
				<option value="<%= patient.id %>" data-url="<%= url_for(patient) %>"><%= patient.lookup_id %></option>
			<% end %>
		</select>
		<h3>Inactive Patients</h3>
		<select name="active-patients">
			<option value="">Please Select</option>
			<% @provider.patients.where(is_active: false).each do |patient| %>
				<option value="<%= patient.id %>" data-url="<%= url_for(patient) %>"><%= patient.lookup_id %></option>
			<% end %>
		</select>
	</div>
	<% end %>
</div>