config/routes.rb
MuscTfcbt::Application.routes.draw do

  get "home/index"
  root :to => "home#index"

  devise_for :providers

  get '/providers/csv' => 'providers#export', as: 'export_providers'

  get '/providers/:id/prepare' => 'providers#prepare', as: 'prepare_providers'
  
  resources :providers do
    resources :patients, only: [:new, :create]
  end
  
  resources :patients, only: [:show, :edit, :update] do
    resources :assignments, only: [:index]
  end
  
  resources :decks, only: [:index, :edit, :update]
  resources :section_questions, only: [:edit, :update]

  put 'patients/:id/assign/:homework_id' => 'patients#assign_homework', as: 'assign_patient_homework'
  put 'patients/:id/deactivate' => 'patients#deactivate', as: 'deactivate_patient'
  put 'patients/:id/activate' => 'patients#activate', as: 'activate_patient'
  put 'patients/:id/start' => 'patients#start_session', as: 'start_patient_session'
  
  resources :chapters, only: [:index, :edit, :show, :update] do
    resources :sections, only: [:show, :create, :destroy]
  end
  
  resources :prepares, only: [:show]
  
  put 'chapters/:chapter_id/sections/:id/finish' => 'sections#finish', as: 'finish_chapter_section'
  put 'chapters/:chapter_id/sections/:id/interaction' => 'sections#interaction', as: 'interaction_chapter_section'
  
  get 'content/edit' => 'content#edit', as: 'edit_content'
  post 'content/edit' => 'content#update_audio_url', as: 'update_audio_url'
  patch 'content' => 'content#update'
  
  get 'homework_category/:id/list' => 'homework_category#list', as: 'list_homework_category'

end

app/models/section.rb
class Section < ActiveRecord::Base
  validates :chapter_id, presence: true
  validates :sequence, uniqueness: { scope: :chapter_id }
  validates :sequence, presence: true
  validates :content_type, inclusion: { in: %w(video), allow_nil: true }

  belongs_to :chapter
  
  has_many :interactions
  has_many :notes
  has_many :decks
  has_many :section_questions

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  before_action :set_audio_url
  before_action :authenticate_provider!
  before_action :validate_active_patient_session, except: [:create, :destroy]
  before_action :validate_chapter_section_exists, except: [:create]
  before_action :validate_chapter_allows_new_sections, only: [:create, :destroy]
  before_action :check_admin, only: [:create, :destroy]
  
  def create
    current_maximum = @chapter.sections.maximum(:sequence)
    section = @chapter.sections.build
    section.sequence = current_maximum.nil? ? 1 : current_maximum + 1
    section.content_type = 'video'
    section.header_text = "Chapter #{@chapter.display_order} Section #{section.sequence}"
    section.save
    redirect_to edit_chapter_path(@chapter)
  end
  
  def destroy
    @section.destroy
    
    current_sequence = 1
    @chapter.sections.each do |s|
      if s.sequence != current_sequence
        s.sequence = current_sequence
        s.save
      end
      current_sequence += 1
    end
    
    redirect_to :back
  end
  
  #/chapters/:chapter_id/sections/:id/
  #note that :id is the 'sequence' of the section within the chapter 
  def show    
    
    @patient = Patient.find(provider_session[:patient_id])
    @section_count = @chapter.sections.count
    @section_current = @section.sequence
    @gender_pronoun_plural = @patient.gender.id == 1 ? "boys" : "girls"
    
    case @chapter.id
    when 1
      case @section.sequence
      when 1
        render 'chapter-01-video'
      when 2
        if @patient.gender.description == "Male"
          render 'chapter-01-boy-front'
        else
          render 'chapter-01-girl-front'
        end
      when 3
        if @patient.gender.description == "Male"
          render 'chapter-01-boy-back'
        else
          render 'chapter-01-girl-back'
        end
      when 4
        if @patient.gender.description == "Male"
          render 'chapter-01-girl-front'
        else
          render 'chapter-01-boy-front'
        end
      when 5
        if @patient.gender.description == "Male"
          render 'chapter-01-girl-back'
        else
          render 'chapter-01-boy-back'
        end
      end

    when 2
      case @section.sequence
      when 1
        render 'chapter-02-video'
      when 2
        @next_session_sequence 
        render 'chapter-02-fast'
      when 3
        render 'chapter-02-slow'
      end
    when 3
      case @section.sequence
      when 1
        render 'chapter-03-video'
      when 2
        if @patient.gender.description == "Male"
          render 'chapter-03-boy'
        else
          render 'chapter-03-girl'
        end
      end
    when 4
      case @section.sequence
      when 1
        render 'chapter-04-video'
      when 2
        if @patient.gender.description == "Male"
          render 'chapter-04-boys'
        else
          render 'chapter-04-girls'
        end
      when 3
        if @patient.gender.description == "Male"
          render 'chapter-04-boys'
        else
          render 'chapter-04-girls'
        end
      end
    when 5
      case @section.sequence
      when 1
        render 'chapter-05-video'
      when 2
        render 'chapter-05-decks'
      when 3
        if params[:deck_id]
        	@deck = Deck.find(params[:deck_id])
        	# associate the interaction with the deck selection screen (@section.id - 1)
			    # originally Interaction.create(section_id: @section.id - 1, patient: @patient, description: "Response", data_key: params[:deck_id], data: 1)
          Interaction.create(section_id: @section.id - 1, patient: @patient, description: "Response", data_key: "deck_index", data: params[:deck_index])
          render 'chapter-05-slides'
		else
			redirect_to patient_assignments_path(@patient)
        end
        
      end
    when 6
      case @section.sequence
      when 1
        render 'chapter-06-video'
      when 2
        render 'chapter-06-writing-feelings'
      when 3
        if @patient.age > 12 then
          render 'chapter-06-measure-feelings-over-12' 
        else
          render 'chapter-06-measure-feelings-under-12'
        end
      when 4
        if @patient.age < 13 || @patient.age > 15
          render 'chapter-06-charades'
        else
          redirect_to chapter_section_path(@chapter.id, @section.sequence + 1)
        end
      when 5
        render 'chapter-06-writing-upsetting-feelings'
      when 6
        render 'chapter-06-writing-traumatic-feelings'
      end
    when 7
      @section_count = 9
      @trackTitles = [
        'My friends are laughing at me.',
        'My friends must have told a funny joke.',
        'I am being left out.'
      ]
      @videos = [
        '98067646',
        '98067515',
        '98067522'
      ]
      @tracks = [
        [0,2,1],
        [1,0,2],
        [2,0,1]
      ]
      case @section.sequence
      when 1
        @section_current = 1
        render 'chapter-07-video'
      when 2
        @section_current = 2
        render 'chapter-07-matching'
      when 3
        @section_current = 2
        render 'chapter-07-matching2'
      when 4
        @section_current = 3
        render 'chapter-07-video2'
      when 5
        @section_current = 4
        render 'chapter-07-best-answer'
      when 6
        @section_current = 5
        render 'chapter-07-multiple-choice'
      when 7
        @section_current = 5
        render 'chapter-07-video3'
      when 8
        @section_current = 5
        render 'chapter-07-multiple-choice2'

        #new sections
      when 9
        @section_current = 5
        render 'chapter-07-video4'
      when 10
        @section_current = 5
        render 'chapter-07-multiple-choice3'
      when 11
        @section_current = 5
        render 'chapter-07-video5'


      when 12
        @section_current = 6
        render 'chapter-07-test'
      when 13
        @section_current = 6
        render 'chapter-07-test-b'
      when 14
        @section_current = 6
        render 'chapter-07-test-c'
      when 15
        @section_current = 6
        render 'chapter-07-test-d'
      when 16
        @section_current = 7
        render 'chapter-07-test-2'
      when 17
        @section_current = 7
        render 'chapter-07-test-2-b'
      when 18
        @section_current = 7
        render 'chapter-07-test-2-c'
      when 19
        @section_current = 7
        render 'chapter-07-test-2-d'
      when 20
        @section_current = 8
        render 'chapter-07-test-3'
      when 21
        @section_current = 8
        render 'chapter-07-test-3-b'
      when 22
        @section_current = 8
        render 'chapter-07-test-3-c'
      when 23
        @section_current = 8
        render 'chapter-07-test-3-d'
      when 24
        @section_current = 8
        render 'chapter-07-video6'
      when 25
        @section_current = 9
        render 'chapter-07-test-4'
      when 26
        @section_current = 9
        render 'chapter-07-test-4-b'
      when 27
        @section_current = 9
        render 'chapter-07-test-4-c'
      when 28
        @section_current = 9
        render 'chapter-07-test-4-d'
      when 29
        @section_current = 9
        render 'chapter-07-test-4-e'
      end
    when 8
      case @section.sequence
      when 1
        render 'chapter-08-video'
      when 2
        render 'chapter-08-decks'
      when 3
      	if params[:deck_id]
	        @deck = Deck.find(params[:deck_id])
	        
	        # associate the interaction with the deck selection screen (@section.id - 1)
	        #Interaction.create(section_id: @section.id - 1, patient: @patient, description: "Response", data_key: params[:deck_id], data: 1)
          Interaction.create(section_id: @section.id - 1, patient: @patient, description: "Response", data_key: "deck_index", data: params[:deck_index])
	        
	        render 'chapter-08-slides'
        
        else
			redirect_to patient_assignments_path(@patient)
        end
        
      end
    when 9

      # Set gender specific details
      if @patient.gender.description == "Male"
        @name = "John"
        @pronoun = "him"
        @possessive = "his"
        @direct = "he"
        @gender = "boy"
      elsif @patient.gender.description == "Female"
        @name = "Jane"
        @pronoun = "her"
        @possessive = "her"
        @direct = "she"
        @gender = "girl"
      end

      # Set audio files
      case @patient.trauma1_id
      when 1
        @section.audio_file = "in-vivo-exposure/#{@gender}/sexual-abuse/#{@section.audio_file}"
      when 2
        @section.audio_file = "in-vivo-exposure/#{@gender}/physical-abuse/#{@section.audio_file}"     
      when 3
        @section.audio_file = "in-vivo-exposure/#{@gender}/accident/#{@section.audio_file}"
      when 4
        @section.audio_file = "in-vivo-exposure/#{@gender}/domestic-violence/#{@section.audio_file}"
      when 5, 7
        @section.audio_file = "in-vivo-exposure/#{@gender}/bullying/#{@section.audio_file}"
      when 6, 8
        @section.audio_file = "in-vivo-exposure/#{@gender}/disaster/#{@section.audio_file}"
      end


      @section_count = 7
      case @section.sequence
      when 1
        @section_current = 1
        render 'chapter-09-video'
      when 2
        @section_current = 2
        @section.audio_file = "in-vivo-exposure/#{@gender}/beginning_narration.mp3"
        render 'chapter-09-audio-test'
      when 3, 4, 5, 6, 7, 8
        @section_current = 3
        case @patient.trauma1_id
        when 1
          render 'chapter-09-audio-a' #sexual abuse
        when 2
          render 'chapter-09-audio-c' #physical abuse          
        when 3
          render 'chapter-09-audio-b' #car crash / accident
        when 4
          render 'chapter-09-audio-e' #domestic violence
        when 5, 7
          render 'chapter-09-audio-f' #school violence / bullying
        when 6, 8
          render 'chapter-09-audio-d' #hurricane / death of a loved one
        when 9
          #other

app/helpers/sections_helper.rb
module SectionsHelper

  def get_vimeo_embed_url(vimeo_id, gender)
  	if vimeo_id != nil && ! vimeo_id.blank?

  		if JSON.is_json?(vimeo_id) && gender
  			vimeo_id = JSON.parse(vimeo_id)[gender]
  		end

  		"//player.vimeo.com/video/#{vimeo_id}?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=0&api=1"
  	end
  end

end

app/views/sections/chapter-01-boy-front.html.erb
<%
	provide(:body_class, 'chapter-01 boy-front')
	provide(:title, "#{@chapter.display_name}")
%>

<div class="stage-top">
	<h2><%= @section.header_text %></h2>
</div>
<div class="stage-bottom">
	<div class="clear">
		<div class="left">
			<ul class="buttons">
				<li><a href="#" class="button breasts righty"><span>Chest</span><em class="tip"></em></a></li>
				<li><a href="#" class="button arms lefty"><span>Arms</span><em class="tip"></em></a></li>
				<li><a href="#" class="button vagina lefty"><span>Penis</span><em class="tip"></em></a></li>
				<li><a href="#" class="button legs righty"><span>Legs</span><em class="tip"></em></a></li>
				<li><a href="#" class="button stomach righty"><span>Stomach</span><em class="tip"></em></a></li>
				<li><a href="#" class="button head lefty"><span>Head</span><em class="tip"></em></a></li>
			</ul>
		</div>
		<div class="right">
			<%= image_tag "boy-front.png", alt: "boy" %>
			<div class="accepts">
				<div class="breasts accept"></div>
				<div class="arms accept"></div>
				<div class="vagina accept"></div>
				<div class="legs accept"></div>
				<div class="stomach accept"></div>
				<div class="head accept"></div>
			</div>
		</div>
		<div class="success-check"></div>
	</div>
	<div class="stage-controls clear">
		<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue', :method => :put %>
		<%= link_to content_tag(:span, 'Skip'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button skip', :method => :put %>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
		<span>Back</span>
		<% end %>
	</div>
</div>

app/views/sections/chapter-06-writing-feelings.html.erb
<%
	provide(:body_class, 'chapter-06 writing')
	provide(:title, "#{@chapter.display_name}")
%>
<div class="stage-top">
	<h2><%= @section.header_text %></h2>
</div>
<div class="stage-bottom">
	<canvas class="canvas" width="756px" height="300px"></canvas>
	<div class="stage-controls clear">
		<div class="stage-controls-calc">
			<div class="lefty">
				<a href="#" class="button small light draw"><span>draw</span></a>
				<a href="#" class="button small light erase"><span>erase</span></a>
			</div>
			<div class="righty">

				<a href="#" class="button green start"><span>Start</span></a>
				<a href="#" class="button gray retry hide"><span>Retry</span></a>
				<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue hide', :method => :put %>

				<%= link_to content_tag(:span, 'Skip'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button skip', :method => :put %>
			</div>
		</div>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
		<span>Back</span>
		<% end %>
	</div>
	<div class="shadow lefty"></div>
	<div class="shadow righty"></div>
</div>

app/views/sections/chapter-06-writing-traumatic-feelings.html.erb
<%
	provide(:body_class, 'chapter-06 writing')
	provide(:title, "#{@chapter.display_name}")
%>
<div class="stage-top">
	<h2><%= @section.header_text %></h2>
</div>
<div class="stage-bottom">
	<canvas class="canvas" width="756px" height="300px"></canvas>
	<div class="stage-controls clear">
		<div class="stage-controls-calc">
			<div class="lefty">
				<a href="#" class="button small light draw"><span>draw</span></a>
				<a href="#" class="button small light erase"><span>erase</span></a>
			</div>
			<div class="righty">
				<a href="#" class="button green start"><span>Start</span></a>
				<a href="#" class="button gray hide"><span>Retry</span></a>
				<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue hide', :method => :put %>
				<%= link_to content_tag(:span, 'Skip'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button skip', :method => :put %>
			</div>
		</div>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
<span>Back</span>
<% end %>

	</div>
	<div class="shadow lefty"></div>
	<div class="shadow righty"></div>
</div>

app/views/sections/chapter-07-multiple-choice2.html.erb
<%
	provide(:body_class, 'chapter-07 best-answer multiple-choice')
	provide(:title, "#{@chapter.display_name}")

	# Get cookies
	track_id = cookies[:chapter07_trackID].to_i
	current_track_position = @tracks[track_id][1].to_i
	track_title = @trackTitles[current_track_position]
%>

<div class="stage-top">
	<h2><%= @section.header_text.gsub("**FEELING**","&ldquo;#{track_title}&rdquo;").html_safe %></h2>
</div>
<div class="stage-bottom">
	<div class="circles clear">
		<%= image_tag 'circle-thoughts.png', alt: 'body', class: 'thoughts inactive' %>
		<%= image_tag 'circle-feelings.png', alt: 'body', class: 'feelings' %>
		<%= image_tag 'circle-actions.png', alt: 'body', class: 'actions inactive' %>
	</div>
	<div class="buttons">
		<% if current_track_position == 1 %>
			<a href="#" class="button hurt"><span>Curious</span></a>
			<a href="#" class="button sad"><span>Happy</span></a>
			<a href="#" class="button angry"><span>Amused</span></a>
			<a href="#" class="button numb"><span>Interested</span></a>
		<% elsif current_track_position == 0 || current_track_position == 2 %>
			<a href="#" class="button hurt"><span>Hurt</span></a>
			<a href="#" class="button sad"><span>Sad</span></a>
			<a href="#" class="button angry"><span>Angry</span></a>
			<a href="#" class="button numb"><span>Numb</span></a>
		<% end %>
	</div>
	<div class="stage-controls clear">
		<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue hidden', :method => :put %>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
		<span>Back</span>
		<% end %>
	</div>
</div>

app/views/sections/chapter-07-test-2.html.erb
<%
	provide(:body_class, 'chapter-07 best-answer multiple-choice')
	provide(:title, "#{@chapter.display_name}")
%>
<div class="stage-top">
	<h2><%= @section.header_text %></h2>
</div>
<div class="stage-bottom">
	<div class="circles clear">
		<%= image_tag 'circle-thoughts.png', alt: 'body', class: 'thoughts' %>
		<%= image_tag 'circle-feelings.png', alt: 'body', class: 'feelings' %>
		<%= image_tag 'circle-actions.png', alt: 'body', class: 'actions' %>
	</div>
<!--
	<div class="buttons">
		<a href="#" class="button hurt"><span>Hurt</span></a>
		<a href="#" class="button sad"><span>Sad</span></a>
		<a href="#" class="button angry"><span>Angry</span></a>
		<a href="#" class="button numb"><span>Numb</span></a>
	</div>
-->
	<div class="stage-controls clear">
		<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue', :method => :put %>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
			<span>Back</span>
		<% end %>
	</div>
</div>

app/views/sections/chapter-07-test-b.html.erb
<%
	provide(:body_class, 'chapter-07 best-answer multiple-choice')
	provide(:title, "#{@chapter.display_name}")
%>
<div class="stage-top">
	<h2><%= @section.header_text %></h2>
</div>
<div class="stage-bottom">
	<div class="circles clear">
		<%= image_tag 'circle-thoughts.png', alt: 'body', class: 'thoughts' %>
		<%= image_tag 'circle-feelings.png', alt: 'body', class: 'feelings inactive' %>
		<%= image_tag 'circle-actions.png', alt: 'body', class: 'actions inactive' %>
	</div>
<!--
	<div class="buttons">
		<a href="#" class="button hurt"><span>Hurt</span></a>
		<a href="#" class="button sad"><span>Sad</span></a>
		<a href="#" class="button angry"><span>Angry</span></a>
		<a href="#" class="button numb"><span>Numb</span></a>
	</div>
-->
	<div class="stage-controls clear">
		<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue', :method => :put %>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
<span>Back</span>
<% end %>



	</div>
</div>

app/views/sections/chapter-07-video2.html.erb
<%
	provide(:body_class, 'chapter-video')
	provide(:title, "#{@chapter.display_name}")

	# Get cookies
	track_id = cookies[:chapter07_trackID].to_i
	video_id = @videos[track_id]
%>
<div class="stage-top">
	<h2><%= @section.header_text %></h2>
</div>
<div class="stage-bottom">
	<div class="clear">
		<%= render partial: 'video', locals: {vimeo_url: 116858533} %>
	</div>
	<div class="stage-controls clear">
		<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue', :method => :put %>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
<span>Back</span>
<% end %>
	</div>
</div>

app/views/sections/chapter-07-video6.html.erb
<%
	provide(:body_class, 'chapter-video')
	provide(:title, "#{@chapter.display_name}")
%>
<div class="stage-top">
	<h2><%= @section.header_text %></h2>
</div>
<div class="stage-bottom">
	<div class="clear">
		<%= render partial: 'video', locals: {vimeo_url: @section.vimeo_url} %>
	</div>
	<div class="stage-controls clear">
		<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue', :method => :put %>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
			<span>Back</span>
		<% end %>
</div>
</div>

app/views/sections/chapter-09-audio-test.erb
<%
	provide(:body_class, 'chapter-09 audio test')
	provide(:title, "#{@chapter.display_name}")
%>
<div class="stage-top">
</div>
<div class="stage-bottom">
	<h3>This chapter contains audio narration. Look for the play button at the top left of each screen. Tap the button to hear the narration. You can pause the narration as it plays, and tap the button again to resume.</h3>
	<h3 class="try">Try it now.</h3>
	
	<%= render partial: 'audio' %>
		
	<div class="stage-controls">
		<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue', :method => :put %>
	</div>
</div>

app/views/sections/chapter-09-ladder-e.html.erb
<%
	provide(:body_class, 'chapter-09 audio ladder')
	provide(:title, "#{@chapter.display_name}")
%>

<div class="stage">
	<div class="stage-top">
		<h2><%= @name %>'s Ladder</h2>
	</div>
	<div class="stage-bottom">
		<div class="clear">
			<div class="ladder-items">
				<div class="ladder-item top">
					<h3 class="one">Hearing other people shout at each other<span class="tip"></span></h3>
				</div>
				<div class="ladder-item">
					<h3 class="two">Watching a movie or show with a man and a woman fighting<span class="tip"></span></h3>
				</div>
				<div class="ladder-item">
					<h3 class="three">Hearing a door slam<span class="tip"></span></h3>
				</div>
				<div class="ladder-item">
					<h3 class="four">Writing a letter to my father<span class="tip"></span></h3>
				</div>
				<div class="ladder-item">
					<h3 class="five">Talking with my mother about domestic violence<span class="tip"></span></h3>
				</div>
			</div>
		</div>
		
		<%= render partial: 'audio' %>
		
		<div class="stage-controls">
			<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue', :method => :put %>
			<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
				<span>Back</span>
			<% end %>
		</div>
	</div>
</div>

app/views/sections/chapter-09-list-d2.html.erb
<%
	provide(:body_class, 'chapter-09 audio list exercise')
	provide(:title, "#{@chapter.display_name}")
%>
<div class="stage">
	<div class="stage-top">
		<h2><%= @name %>'s List</h2>
	</div>
	<div class="stage-bottom">
		<div class="clear">
			<div class="list"></div>
			<div class="list-items">
				<div class="tip"></div>
				<h3>1. Having a funeral for my dog<span class="bar"></span></h3><br />
				<h3>2. Walking outside during a severe tropical storm<span class="bar"></span></h3><br />
				<h3>3. Watching a storm through a window<span class="bar"></span></h3><br />
				<h3>4. Talking to family and friends who were also affected by the Hurricane<span class="bar"></span></h3><br />
				<h3>5. Moving to a place that doesn’t have disasters<span class="bar"></span></h3><br />
				<h3>6. Watching a video or news show about the Hurricane<span class="bar"></span></h3><br />
				<h3>7. Looking through old pictures of my dog and my house<span class="bar"></span></h3><br />
				<h3 class="crossed">8. Giving a presentation to my class<span class="bar"></span></h3><br />
			</div>
		</div>
		
		<%= render partial: 'audio' %>
		
		<div class="stage-controls">
			<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue', :method => :put %>
			<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
				<span>Back</span>
			<% end %>
		</div>
	</div>
</div>

app/views/sections/chapter-09-list-e3.html.erb
<%
	provide(:body_class, 'chapter-09 audio list exercise')
	provide(:title, "#{@chapter.display_name}")
%>
<div class="stage">
	<div class="stage-top">
		<h2><%= @name %>'s List</h2>
	</div>
	<div class="stage-bottom">
		<div class="clear">
			<div class="list"></div>
			<div class="list-items">
				<div class="tip"></div>
				<h3>1. Hearing other people shout at each other<span class="bar"></span></h3><br />
				<h3 class="crossed">2. Sneaking out of the house when I need space<span class="bar"></span></h3><br />
				<h3>3. Writing a letter to my father<span class="bar"></span></h3><br />
				<h3>4. Watching a movie or show with a man and a woman fighting<span class="bar"></span></h3><br />
				<h3>5. Confronting my father in jail<span class="bar"></span></h3><br />
				<h3>6. Hearing a door slam<span class="bar"></span></h3><br />
				<h3>7. Talking with my mother about domestic violence<span class="bar"></span></h3><br />
				<h3 class="crossed">8. Giving a presentation to my class<span class="bar"></span></h3><br />
			</div>
		</div>
		
		<%= render partial: 'audio' %>
		
		<div class="stage-controls">
			<%= link_to content_tag(:span, 'Continue'), finish_chapter_section_path(@chapter, @section.sequence), class: 'button green continue', :method => :put %>
			<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
				<span>Back</span>
			<% end %>
		</div>
	</div>
</div>

app/views/sections/chapter-11-index.html.erb
<%
	provide(:body_class, 'misc patient chapters')
	provide(:title, "Parenting")
%>

<div class="stage-top">
	<h2>Parenting</h2>
</div>
<div class="stage-bottom">
	<h3>Select a Topic</h3>
	
	<div class="chapter-buttons clear">
	<% current_provider.decks.where(section_id:@section).each_with_index do |deck,index| %>
		<%= link_to content_tag(:span, "#{index+1} - #{deck.title}"), chapter_section_path(@chapter,@section.sequence+1, deck_id: deck.id, deck_index: index + 1), class: 'button green' %>
	<% end %>
	</div>

	<div class="stage-controls">
	<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
		<span>Back</span>
	<% end %>
	</div>
</div>