config/routes.rb
MuscTfcbt::Application.routes.draw do

  get "home/index"
  root :to => "home#index"

  devise_for :providers

  get '/providers/csv' => 'providers#export', as: 'export_providers'

  get '/providers/:id/prepare' => 'providers#prepare', as: 'prepare_providers'
  
  resources :providers do
    resources :patients, only: [:new, :create]
  end
  
  resources :patients, only: [:show, :edit, :update] do
    resources :assignments, only: [:index]
  end
  
  resources :decks, only: [:index, :edit, :update]
  resources :section_questions, only: [:edit, :update]

  put 'patients/:id/assign/:homework_id' => 'patients#assign_homework', as: 'assign_patient_homework'
  put 'patients/:id/deactivate' => 'patients#deactivate', as: 'deactivate_patient'
  put 'patients/:id/activate' => 'patients#activate', as: 'activate_patient'
  put 'patients/:id/start' => 'patients#start_session', as: 'start_patient_session'
  
  resources :chapters, only: [:index, :edit, :show, :update] do
    resources :sections, only: [:show, :create, :destroy]
  end
  
  resources :prepares, only: [:show]
  
  put 'chapters/:chapter_id/sections/:id/finish' => 'sections#finish', as: 'finish_chapter_section'
  put 'chapters/:chapter_id/sections/:id/interaction' => 'sections#interaction', as: 'interaction_chapter_section'
  
  get 'content/edit' => 'content#edit', as: 'edit_content'
  post 'content/edit' => 'content#update_audio_url', as: 'update_audio_url'
  patch 'content' => 'content#update'
  
  get 'homework_category/:id/list' => 'homework_category#list', as: 'list_homework_category'

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  validates :name, presence: true
  validates :display_order, presence: true

  has_many :sections

  def display_name
    return "#{display_order} - #{name}"
  end

  def first_vimeo_url
    sections.first.vimeo_url
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

  before_action :authenticate_provider!
  before_action :validate_active_patient_session, except: [:edit, :update]

  def index
    @patient = Patient.find(provider_session[:patient_id])
    render 'index'
  end
  
  def edit
    @chapter = Chapter.find(params[:id])
  end
  
  def update
  	@chapter = Chapter.find(params[:id])

  	@chapter.name = params["chapter"]["name"]
  	@chapter.prepare_vimeo_url = params["chapter_prepare_vimeo_url"]
	
  	@chapter.save
	
  	first_section = @chapter.sections.first
    unless first_section.nil?
    	first_section.vimeo_url = params["chapter_vimeo_url"]
    	first_section.save
    end
    
    @chapter.sections.all.each do |section|
      if params.key?("section_#{section.id}_header_text")
        section.header_text = params["section_#{section.id}_header_text"]
        section.save
      end
    
      if params.key?("section_#{section.id}_body_text")
        section.body_text = params["section_#{section.id}_body_text"]
        section.save
      end
      
      if params.key?("section_#{section.id}_audio_file")
        section.audio_file = params["section_#{section.id}_audio_file"]
        section.save
      end
      
      if params.key?("section_#{section.id}_vimeo_url")
        section.vimeo_url = params["section_#{section.id}_vimeo_url"]
        section.save
      end
      
      section.notes.all.each_with_index do |note, index|
      	if params.key?("section_#{section.id}_note_#{index + 1}")
      		note.content = params["section_#{section.id}_note_#{index + 1}"]
      		note.save
      	end
      end
      
      section.section_questions.all.each_with_index do |question, index|
        if params.key?("section_#{section.id}_question_#{question.sequence}")
          question.question = params["section_#{section.id}_question_#{question.sequence}"]
          question.answer_boys = params["section_#{section.id}_question_#{question.sequence}_answer_boys"]
          question.answer_girls = params["section_#{section.id}_question_#{question.sequence}_answer_girls"]
          question.save
        end
      end
      
    end
    
    redirect_to edit_content_path
  end
  
  def show
    @chapter = Chapter.find(params[:id])
    @section = @chapter.sections.order(:sequence).first
    redirect_to chapter_section_path(@chapter, @section.sequence)
  end
  
  private
    
    def chapter_params
      params.require(:chapter).permit(:name, :prepare_vimeo_url)
    end

end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/edit.html.erb
<% 
	provide(:body_class, 'misc content-edit edit-chapter')
	provide(:title, 'Edit Chapter') 
%>

<%= form_for(@chapter) do |f| %>


<div class='stage-top'>
	<h2>Edit Chapter <%= @chapter.display_name %></h2>
</div>
<div class='stage-bottom clear'>
	
	<div class="stage-bottom-content">
		
		<h3><%= link_to "View Chapter", chapter_path(@chapter.id), :target => "_blank" %></h3>
	
		<div class="input-row">
			<%= label_tag "chapter_name", "Chapter Title:" %>
			<%= f.text_field :name, :required => true %>
		</div>
		
		<% unless @chapter.sections.first.nil? %>
			<div class="input-row">
				<%= label_tag "chapter_vimeo_url", "Chapter Introduction Video:"%>
				<%= text_field_tag "chapter_vimeo_url", "#{@chapter.sections.first.vimeo_url}" %>
			</div>
		<% end %>
		
		<div class="input-row">
			<%= label_tag "chapter_prepare_vimeo_url", "Chapter Preparation Video:"%>
			<%= text_field_tag "chapter_prepare_vimeo_url", "#{@chapter.prepare_vimeo_url}" %>
		</div>
	
		<h3>Sections 
			<% if @chapter.id == 11 %>
				(<%= link_to 'Add new', chapter_section_path(@chapter, nil), method: 'post' %>)
			<% end %>
		</h3>
		<% @chapter.sections.order(:sequence).each do |section| %>
			<div class="input-row">
				<% if @chapter.id == 11 %>
					<%= link_to "Delete section #{section.sequence}", chapter_section_path(@chapter, section.sequence), method: 'delete' %>
				<% end %>
				
				<% unless section.header_text.nil? %>
				<%= label_tag "section_#{section.id}_header_text", "Section #{section.sequence} Caption:" %>
				<%= text_field_tag "section_#{section.id}_header_text", section.header_text %>
				<% end %>
				<% unless section.body_text.nil? %>
				<%= label_tag "section_#{section.id}_body_text", "Section #{section.sequence} Body Text:" %>
				<%= text_field_tag "section_#{section.id}_body_text", section.body_text %>					
				<% end %>
				<% unless section.audio_file.nil? %>
				<%= label_tag "section_#{section.id}_audio_file", "Section #{section.sequence} Audio File:" %>
				<%= text_field_tag "section_#{section.id}_audio_file", section.audio_file %>					
				<% end %>

				<% if @chapter.id == 11 %>
					<div class="input-row">
						<%= label_tag "section_#{section.id}_vimeo_url", "Section #{section.sequence} video:"%>
						<%= text_field_tag "section_#{section.id}_vimeo_url", "#{section.vimeo_url}" %>
					</div>
				<% end %>
				
				<% section.notes.each_with_index do |note, index| %>
				<%= label_tag "section_#{section.id}_note_#{index + 1}", "Section #{section.sequence} Note #{index + 1}:" %>
				<%= text_area_tag "section_#{section.id}_note_#{index + 1}", note.content %>
				<% end %>
	
				<% section.section_questions.order(:sequence).each_with_index do |question, index| %>
				<%= label_tag "section_#{section.id}_question_#{question.sequence}", "Section #{section.sequence} question #{question.sequence}:" %>
				<%= text_field_tag "section_#{section.id}_question_#{question.sequence}", question.question %>
				<%= text_field_tag "section_#{section.id}_question_#{question.sequence}_answer_boys", question.answer_boys %>
				<%= text_field_tag "section_#{section.id}_question_#{question.sequence}_answer_girls", question.answer_girls %>
				<% end %>
				

			</div>
		<% end %>
		
		<h3>Decks</h3>
		<ul>
		<% @chapter.sections.each do |section| %>
			<% section.decks.each do |deck| %>
				<li><%= link_to "#{deck.title}", edit_deck_path(deck.id) %></li>
			<% end %>
		<% end %>
		</ul>
	
	</div>
	
	<div class="stage-controls clear">
		<a href="#" class="button green save"><span onclick="document.getElementById('edit_chapter_<%= @chapter.id %>').submit();">Save Changes</span></a>
		<%= link_to 'javascript:history.back()', class: 'button blue back' do %>
			<span>Back</span>
		<% end %>
	</div>
	
</div>

<% end %>

app/views/chapters/index.html.erb
<%
	provide(:body_class, 'misc patient chapters')
	provide(:title, "#{@patient.lookup_id}'s home screen")
%>

<div class="stage-top">
	<h2><%= @patient.lookup_id %></h2>
</div>
<div class="stage-bottom">
	<h3>Choose a chapter.</h3>
	
	<div class="chapter-buttons">
	<% Chapter.all.order("display_order ASC").each do |chapter| %>
		<% if chapter.display_order % 2 == 1 %>
			<div class="button-row clear">
		<% end %>

			<%= link_to content_tag(:span, chapter.display_name), chapter_path(chapter.id), class: 'button green' %>

		<% if chapter.display_order % 2 == 1 %>
			<div>
		<% end %>
	<% end %>
	</div>
</div>