config/routes.rb
MuscTfcbt::Application.routes.draw do

  get "home/index"
  root :to => "home#index"

  devise_for :providers

  get '/providers/csv' => 'providers#export', as: 'export_providers'

  get '/providers/:id/prepare' => 'providers#prepare', as: 'prepare_providers'
  
  resources :providers do
    resources :patients, only: [:new, :create]
  end
  
  resources :patients, only: [:show, :edit, :update] do
    resources :assignments, only: [:index]
  end
  
  resources :decks, only: [:index, :edit, :update]
  resources :section_questions, only: [:edit, :update]

  put 'patients/:id/assign/:homework_id' => 'patients#assign_homework', as: 'assign_patient_homework'
  put 'patients/:id/deactivate' => 'patients#deactivate', as: 'deactivate_patient'
  put 'patients/:id/activate' => 'patients#activate', as: 'activate_patient'
  put 'patients/:id/start' => 'patients#start_session', as: 'start_patient_session'
  
  resources :chapters, only: [:index, :edit, :show, :update] do
    resources :sections, only: [:show, :create, :destroy]
  end
  
  resources :prepares, only: [:show]
  
  put 'chapters/:chapter_id/sections/:id/finish' => 'sections#finish', as: 'finish_chapter_section'
  put 'chapters/:chapter_id/sections/:id/interaction' => 'sections#interaction', as: 'interaction_chapter_section'
  
  get 'content/edit' => 'content#edit', as: 'edit_content'
  post 'content/edit' => 'content#update_audio_url', as: 'update_audio_url'
  patch 'content' => 'content#update'
  
  get 'homework_category/:id/list' => 'homework_category#list', as: 'list_homework_category'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  validates :homework_id, presence: true, uniqueness: { scope: :patient_id }
  validates :patient_id, presence: true

  belongs_to :homework
  belongs_to :patient
  
end

app/models/card.rb
class Card < ActiveRecord::Base  
  belongs_to :deck
  has_many :notes

  after_initialize :init

    def init
      self.card_order  ||= self.id
    end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  validates :name, presence: true
  validates :display_order, presence: true

  has_many :sections

  def display_name
    return "#{display_order} - #{name}"
  end

  def first_vimeo_url
    sections.first.vimeo_url
  end

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :provider  
  belongs_to :section
  has_many :cards, :order => 'card_order ASC'

  accepts_nested_attributes_for :cards
  
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  validates :description, presence: true
  
  has_many :providers
end

app/models/ethnicity.rb
class Ethnicity < ActiveRecord::Base
  has_many :patients
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  validates :description, presence: true
  
  has_many :providers
  
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  has_many :patients
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  validates   :description, presence: true
  
  belongs_to  :homework_category
  
  has_many    :assignments
  has_many    :patients, through: :assignments

end

app/models/interaction.rb
class Interaction < ActiveRecord::Base
  validates :description, presence: true, inclusion: { in: %w(Visit Response) }
  validates :patient_id, presence: true
  validates :section_id, presence: true
  
  belongs_to :patient
  belongs_to :section
  
end

app/models/note.rb
class Note < ActiveRecord::Base
	validates :content, presence: true
  
	belongs_to :section
	belongs_to :card
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validates   :lookup_id, presence: true
  validates   :provider_id, presence: true
  validates   :age, presence: true
  validates   :race_id, presence: true
  validates   :ethnicity_id, presence: true
  validates   :gender_id, presence: true
  validates   :trauma1_id, presence: true
  
  belongs_to  :race
  belongs_to  :ethnicity
  belongs_to  :gender
  belongs_to  :provider
  
  belongs_to :trauma1, :class_name => "Trauma", :foreign_key => "trauma1_id"
  belongs_to :trauma2, :class_name => "Trauma", :foreign_key => "trauma2_id"
  belongs_to :trauma3, :class_name => "Trauma", :foreign_key => "trauma3_id"
  belongs_to :trauma4, :class_name => "Trauma", :foreign_key => "trauma4_id"
  
  has_many    :interactions, :dependent => :destroy
  has_many    :assignments, :dependent => :destroy
  has_many    :homeworks, through: :assignments
  
  before_create :default_values
  
  private
    def default_values
      is_active ||= true
    end
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  validates :description, presence: true
  
  has_many :providers
  
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # bwj removed :rememberable, :registerable  until we get there
  devise :database_authenticatable, :trackable, :validatable, :timeoutable, :recoverable
         
  validates   :name, presence: true, length: { maximum: 100 }
  validates   :email, presence: true, uniqueness: {case_sensitive: false }
  validates   :password, presence: true, length: { minimum: 8 }, on: :create
  validates   :password, length: { minimum: 8 }, on: :update, allow_blank: true
  
  belongs_to  :profession
  belongs_to  :degree
  belongs_to  :experience
  
  has_many    :patients, :dependent => :destroy
  has_many    :decks, :dependent => :destroy
  
  before_save { self.email = email.downcase }
  
  after_create :set_decks
    def set_decks
      provider_id = self.id
      Deck.where(original: true).each do |deck|
        deck_copy = deck.deep_clone :include => {:cards => :notes}
        deck_copy.provider_id = provider_id
        deck_copy.original = false
        deck_copy.save
      end
    end
end

app/models/race.rb
class Race < ActiveRecord::Base
  has_many :patients
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates :chapter_id, presence: true
  validates :sequence, uniqueness: { scope: :chapter_id }
  validates :sequence, presence: true
  validates :content_type, inclusion: { in: %w(video), allow_nil: true }

  belongs_to :chapter
  
  has_many :interactions
  has_many :notes
  has_many :decks
  has_many :section_questions

end

app/models/trauma.rb
class Trauma < ActiveRecord::Base
  validates :description, presence: true

end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/_header.html.erb
<header class="site-header clear">
	<div class="tame clear">
		<h1><%= yield(:title) %></h1>
		<% unless @section_count.nil? || @section_current.nil? %>
			<ul class="pages">
				<% (1..@section_count).each do |index| %>
					<% if index < @section_current  %>
						<li class="completed"><%= index %></li>
					<% elsif index == @section_current %>
						<li class="current"><%= index %></li>
					<% else %>
						<li><%= index %></li>
					<% end %>
				<% end %>
			</ul>
		<% end %>
		<nav class="site-navigation">
			<ul class="top-navigation">
				<li class="menu"><a href="#">Menu</a>
					<ul class="sub-navigation">
						<% if provider_signed_in? %>
							<% unless provider_session[:patient_id].nil? %>
								<li class="home"><%= link_to 'Home', chapters_path %></li>
								<li class="homework"><%= link_to 'Homework', patient_assignments_path(provider_session[:patient_id])%></li>
							<% end %>
							<li class="end-session"><%= link_to('End Session', provider_path(current_provider))%></li>
						<% end %>
					</ul>
				</li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_notes.html.erb
<%

@note_content = ''
@card_notes = false
@section_notes = false
@note_index = 0

if @deck
	@deck.cards.where(active:true).each do |card|
		if card.notes.count > 0
			@card_notes = true
		end
	end
elsif @section
	if @section.notes.first()
		@note_content = @section.notes.first.content
		@section_notes = true
	end
end

%>

<% if @card_notes || @section_notes %>

<div class="provider-notes">
	<div class="tab">
		<h5>Provider</h5>
	</div>
	<div class="notes">
		<h3>Notes</h3>
		<% if @card_notes %>
			<% @deck.cards.where(active:true).each_with_index do |card, card_index| %>

				<div class="note" data-card-id="card-<%= card_index + 1 %>">
					<%= raw card.notes.first.content if card.notes.first %>
				</div>

			<% end %>
		<% elsif @section_notes %>
			<div class="note">
				<%= raw @note_content %>
			</div>
		<% end %>
	</div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en-US">
<!--<![endif]-->
	<head>
	<title>MUSC TFCBT</title>
	<meta charset="UTF-8" />
	<meta name="description" content="MUSC TFCBT" />
	<meta name="keywords" content="" />
	<meta name="viewport" content="width=1020, user-scalable=0;"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="format-detection" content="telephone=no">
	<meta name="apple-mobile-web-app-capable" content="yes">

	<link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>"/>
	<link rel="apple-touch-icon" href="<%= asset_path 'favicon.png' %>">

	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

	<script type="text/javascript" src="//use.typekit.net/sss7zpf.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

	</head>
	<body class="<%= yield(:body_class) %>">
		<div class="wrap">
			<%= render 'layouts/header' %>
			<!-- todo bwj add these back / style
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
			-->
			<div class="content tame">
				<section class="stage">
					<%= yield %>
					<%= render 'layouts/notes' %>
				</section><!-- stage -->
			</div><!-- content -->
			<div class="push"></div>
		</div><!-- wrap -->
	</body>
</html>